#!/bin/bash


# Config
#export MAP_FILE="/assets/data/testmap.txt"
#export COMMANDERS="se.ramn.bottfarmen.example.baseraider.BaseRaiderCommander,se.ramn.bottfarmen.example.idle.IdleCommander"
#export LOG_LEVEL=Debug
#export EXTRA_CLASSPATH="path/to/some.jar:path/to/another.jar"


function run_with_sbt() {
  exec sbt "project bottfarmen-desktop" "run"
}

function build_and_run_jar() {
  sbt assembly
  DESKTOP_STARTER_JAR="desktop/target/scala-2.10/bottfarmen-desktop-assembly-0.1.jar"
  exec java -cp "$DESKTOP_STARTER_JAR:$EXTRA_CLASSPATH" se.ramn.bottfarmen.DesktopStarter
}

build_and_run_jar
